obj-$(CONFIG_RSC_V2) := rsc_core.o rsc_sys_api.o
obj-$(CONFIG_RSC_V2_CPU_CAP_NOTIFY) += rsc_cpu_capability.o
obj-$(CONFIG_RSC_TASK_CPU_USAGE) += rsc_cpu_usage.o
obj-$(CONFIG_RSC_UID_IO) += rsc_uid_io.o
obj-$(CONFIG_RSC_CHECK_LMK) += rsc_lmk_stat.o
obj-$(CONFIG_RSC_CPU_TOP) += rsc_cpu_top.o
obj-$(CONFIG_RSC_IOLIMIT) += rsc_iolimit.o